### ISSUE TITLE
Publicar publicamente.

### ISSUE THREAD

**Issue by nahytar** [nahytar/scl-2018-05-bc-core-am-socialnetwork#18]
El usuario debe poder publicar públicamente, visible para todos los usuarios de la red social.

**Comment by LeslieInostroza** [comment]
ya se puede publicar publicamente, pero se quintiplica y se mandas post vacios ( se esta arreglando)

**Comment by LeslieInostroza** [comment]
ya no se quintiplica

**Comment by LeslieInostroza** [comment]
el usuario puede publicar publicamente
